openapi: 3.1.0
info:
  title: OutFoxed API
  version: 1.0.0
servers:
  - url: https://outfoxed-backend.onrender.com
paths:
  /start-timer:
    post:
      operationId: startPomodoroTimer
      summary: Start a Pomodoro timer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: integer
                  description: Duration of the timer in minutes
                  default: 25
      responses:
        "200":
                       message:
                type: string
              note:
                type: string
              suggestion:
                type: string
              tip:
                type: string
              duration:
                type: integer

