openapi: 3.1.0
info:
  title: OutFoxed API
  version: 1.0.0
servers:
  - url: https://outfoxed-backend.onrender.com
paths:
  /start-timer:
    post:
      operationId: startPomodoroTimer
      summary: Start a Pomodoro timer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: integer
                  description: Duration of the timer in minutes
                  default: 25
      responses:
        "200":
          description: Timer started message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  note:
                    type: string
                  suggestion:
                    type: string
                  tip:
                    type: string
                  duration:
                    type: integer

  /log-session:
    post:
      operationId: logSession
      summary: Log the result of a completed focus session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                  description: What the user accomplished during the session
                mood:
                  type: string
                  description: Optional mood descriptor (e.g., focused, stressed, proud)
                category:
                  type: string
                  description: Optional tag for grouping logs (e.g., work, school, self-care)

      responses:
        "200":
          description: Session logged confirmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  summary:
                    type: string
                  mood:
                    type: string
                  category:
                    type: string

